version: '3.8'
services:
  redis:
    image: library/redis:6.0
    container_name: p2p_redis
    command: redis-server --requirepass 29431
    restart: unless-stopped
    volumes:
      - ./redis/data:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - "6380:6379"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M

  mongo:
    image: mongo
    build: ./mongo
    restart: unless-stopped
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: exchange_db
      MONGO_REPLICA_HOST: host.docker.internal
      MONGO_REPLICA_PORT: 27018
    ports:
      - '27018:27018'
    command: ["mongod", "--bind_ip_all", "--port", "27017", "--auth",]
