module.exports = {
  root: true,
  parser: "@typescript-eslint/parser",
  plugins: [
    "import",
    "prettier",
    "@typescript-eslint",
    "@typescript-eslint/eslint-plugin",
    "simple-import-sort",
  ],
  extends: [
    "plugin:@typescript-eslint/recommended",
    "plugin:prettier/recommended",
    "prettier",
  ],
  env: { node: true, jest: true, es6: true },
  rules: {
    "prettier/prettier": [
      "error",
      {
        trailingComma: "all",
        semi: true,
        printWidth: 100,
        tabWidth: 2,
        endOfLine: "auto",
        arrowParens: "always",
        singleQuote: true,
        useTabs: false,
      },
    ],
    "no-unused-vars": "off",
    "no-trailing-spaces": ["error", { skipBlankLines: true }],
    "no-multiple-empty-lines": "error",
    "no-use-before-define": ["error", { functions: false, classes: false }],
    "newline-after-var": ["error", "always"],
    quotes: ["error", "single"],
    semi: ["error", "always"],
    "no-console": ["error"],
    "no-debugger": ["warn"],
    //
    "import/no-unresolved": "off",
    "import/extensions": "off",
    "import/no-extraneous-dependencies": "off",
    "simple-import-sort/imports": "error",
    "simple-import-sort/exports": "error",
    //
    "@typescript-eslint/interface-name-prefix": "off",
    "@typescript-eslint/semi": [2, "always"],
    "@typescript-eslint/no-unused-vars": ["error"],
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/explicit-module-boundary-types": "off",
    "@typescript-eslint/no-explicit-any": "off",
  },
};
